version: "3.5"

services:
    app:
        container_name: projeto-cms-bruno-php
        image: local-php:8.1-apache
        user: "1000:1000"
        build:
            context: ./
            dockerfile: ./.docker/php/Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/html
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./.docker/apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
        links:
            - mysql
        working_dir: /var/www/html
        ports:
            - "80:80"
    mysql:
        container_name: projeto-cms-bruno-mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./.mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: projeto-cms
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
